### ISSUE TITLE
0.0.1.3 Crashing Game?

### ISSUE THREAD

**Issue by hungrysloth128** [marconsou/deep-dungeon-tracker#1]
[dalamud_appcrash_20221225_141231_450_12552.log](https://github.com/marconsou/deep-dungeon-tracker/files/10300525/dalamud_appcrash_20221225_141231_450_12552.log)

**Comment by marconsou** [comment]
hmn, I don't see any trace of Deep Dungeon Tracker crashing it:
```
at System.Environment.get_StackTrace()

   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70

   at ImGuiNET.ImGuiNative.igNewFrame()

   at ImGuiNET.ImGuiNative.igNewFrame()

   at ImGuiScene.RawDX11Scene.Render() in D:\a\Dalamud\Dalamud\lib\ImGuiScene\ImGuiScene\RawDX11Scene.cs:line 140

   at Dalamud.Interface.Internal.InterfaceManager.PresentDetour(IntPtr swapChain, UInt32 syncInterval, UInt32 presentFlags) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 550

   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 458
```

It seems to be something related do DirectX 11 or something with Dalamud itself.

Send me your Dalamud.log and Output.log just to make sure

**Comment by hungrysloth128** [comment]
[dalamud.log](https://github.com/marconsou/deep-dungeon-tracker/files/10300695/dalamud.log)
[output.log](https://github.com/marconsou/deep-dungeon-tracker/files/10300696/output.log)

ty appreciate the help

**Comment by marconsou** [comment]
It seems to be the other plugin DeepDungeonDex (which is not related with this project):
(Some json file reading-related error)
```
2022-12-25 13:50:58.685 -05:00 [ERR] [PLUGINR] PluginMaster failed: https://github.com/Strati/DeepDungeonDex/find/master
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\PluginRepository.cs:line 98
```
Another issue your plugins are not loading properly it seems:

```
2022-12-25 17:12:39.932 -05:00 [ERR] [LOCALPLUGIN] **Error while loading ezWondrousTails**,

Dalamud.Plugin.Internal.Exceptions.InvalidPluginOperationException: Plugin was not loaded as per policy
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 329
2022-12-25 17:12:39.932 -05:00 [INF] [PLUGINM] Regular plugin failed to load, adding anyways: WondrousTailsSolver.dll
Dalamud.Plugin.Internal.Exceptions.InvalidPluginOperationException: Plugin was not loaded as per policy
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 329
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 871
2022-12-25 17:12:39.933 -05:00 [INF] [PLUGINM] Loading plugin Duty Tracker
2022-12-25 17:12:39.937 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0xMi0yNVQxNzoxMjozOS45MzcyMzMyLTA1OjAwIiwiSW5mbyI6IkRhbGFtdWQuUGx1Z2luLkludGVybmFsLkV4Y2VwdGlvbnMuSW52YWxpZFBsdWdpbk9wZXJhdGlvbkV4Y2VwdGlvbjogUGx1Z2luIHdhcyBub3QgbG9hZGVkIGFzIHBlciBwb2xpY3lcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uTG9hZEFzeW5jKFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIHJlbG9hZGluZykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcVHlwZXNcXExvY2FsUGx1Z2luLmNzOmxpbmUgMzI5IiwiQ29udGV4dCI6IltMT0NBTFBMVUdJTl0gRXJyb3Igd2hpbGUgbG9hZGluZyBQZW5ueSBQaW5jaGVyIn0=

2022-12-25 17:12:39.937 -05:00 [ERR] [LOCALPLUGIN] Error while loading Penny Pincher

Dalamud.Plugin.Internal.Exceptions.InvalidPluginOperationException: Plugin was not loaded as per policy
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 329
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 871
2022-12-25 17:12:39.937 -05:00 [INF] [PLUGINM] Regular plugin failed to load, adding anyways: PennyPincher.dll
Dalamud.Plugin.Internal.Exceptions.InvalidPluginOperationException: Plugin was not loaded as per policy
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 329
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 871
2022-12-25 17:12:39.937 -05:00 [INF] [PLUGINM] Loading plugin Price Insight
2022-12-25 17:12:39.971 -05:00 [INF] [PLUGINM] Loading plugin Quest Map
2022-12-25 17:12:40.019 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0xMi0yNVQxNzoxMjo0MC4wMTkyNTkyLTA1OjAwIiwiSW5mbyI6IkRhbGFtdWQuUGx1Z2luLkludGVybmFsLkV4Y2VwdGlvbnMuSW52YWxpZFBsdWdpbk9wZXJhdGlvbkV4Y2VwdGlvbjogUGx1Z2luIHdhcyBub3QgbG9hZGVkIGFzIHBlciBwb2xpY3lcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuVHlwZXMuTG9jYWxQbHVnaW4uTG9hZEFzeW5jKFBsdWdpbkxvYWRSZWFzb24gcmVhc29uLCBCb29sZWFuIHJlbG9hZGluZykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcVHlwZXNcXExvY2FsUGx1Z2luLmNzOmxpbmUgMzI5IiwiQ29udGV4dCI6IltMT0NBTFBMVUdJTl0gRXJyb3Igd2hpbGUgbG9hZGluZyBEdXR5IFRyYWNrZXIifQ==
2022-12-25 17:12:40.019 -05:00 [ERR] [LOCALPLUGIN] Error while loading Duty Tracker
Dalamud.Plugin.Internal.Exceptions.InvalidPluginOperationException: Plugin was not loaded as per policy
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 329
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 871
2022-12-25 17:12:40.019 -05:00 [INF] [PLUGINM] Regular plugin failed to load, adding anyways: DutyTracker.dll
Dalamud.Plugin.Internal.Exceptions.InvalidPluginOperationException: Plugin was not loaded as per policy
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 329
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 871
2022-12-25 17:12:40.019 -05:00 [INF] [PLUGINM] Loading plugin Kiko Guide
2022-12-25 17:12:40.024 -05:00 [INF] 
```

In this case you should upload the Dalamud.log into the plugins-generals, then the people there will gonna help with this issue.

**Comment by hungrysloth128** [comment]
I just updated drivers + Windows and that seemed to fix it! Weird it was crashing with this plugin specifically. Thanks for the help though (and the plugin as well is amazing).

**Comment by marconsou** [comment]
The issue still happening?

**Comment by hungrysloth128** [comment]
yeah. I'm not sure why or how, but it's this specific plugin that's causing it. I've tried disabling everything else except for it and reinstalled too. Idk what it is but it's since yesterday's update.

Here's the latest crash: 
[dalamud_appcrash_20221225_204400_252_6220.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301048/dalamud_appcrash_20221225_204400_252_6220.log)

**Comment by marconsou** [comment]
Send the Dalamug.log, when exactly crashes?

**Comment by hungrysloth128** [comment]
[dalamud.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301114/dalamud.log)
![Screenshot (4)](https://user-images.githubusercontent.com/60623734/209489802-ce0ee5fc-fdbf-49aa-bbfe-54dcdab78af6.png)
It always crashes at this exact moment after I click my character.
I've been using it perfectly fine up until 0.0.1.3

**Comment by marconsou** [comment]
When you open the Statistic Window (your save file)?

**Comment by hungrysloth128** [comment]
So I deleted my save file in statistics and managed to log on, but right when I clocked "show" on the overlay it did the same thing. 

![Screenshot (5)](https://user-images.githubusercontent.com/60623734/209490098-96a52a17-9e06-466e-a624-ab384300e8be.png)

**Comment by marconsou** [comment]
Show option in which menu?

**Comment by hungrysloth128** [comment]
I think there's something with the save too. It works fine at startup like below. 

![Screenshot (6)](https://user-images.githubusercontent.com/60623734/209490333-6643c482-0c42-48e0-b808-9b495fef23c3.png)

But right when I click my save file it crashes
![Screenshot (7)](https://user-images.githubusercontent.com/60623734/209490364-0316919d-7169-4024-b860-5f9d4826b95f.png)

where's the save located?

**Comment by marconsou** [comment]
%AppData%\XIVLauncher\pluginConfigs\DeepDungeonTracker

**Comment by hungrysloth128** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/60623734/209490701-e7848fa5-eb57-4f2f-8c73-6f303479f50e.png)
which of these is it?

**Comment by hungrysloth128** [comment]
I could switch options for floors fine. Every setting seems to work fine on the startup screen. 
![Screenshot (10)](https://user-images.githubusercontent.com/60623734/209490737-5683a34a-a67b-48e0-a82d-1ce8a2e6b5af.png)

But immediately when clicking on the save file I get the crash
![Screenshot (11)](https://user-images.githubusercontent.com/60623734/209490783-511a265b-0c70-4434-bf06-a0f6321a2c74.png)

**Comment by marconsou** [comment]
These are the plugin dll, the save is inside pluginConfig folder. (I've posted the link above)

**Comment by marconsou** [comment]
Now i need to know if it is the save file which is causing the crash, you gonna need to send me the file.
%AppData%\XIVLauncher\pluginConfigs\DeepDungeonTracker
Folder shortcut

**Comment by hungrysloth128** [comment]
Thanks found it. There's 2 for some reason even though I only have 1 file in game. How can I send it? Won't accept here.

**Comment by marconsou** [comment]
Just drag and drop the file in the edit text box, if is not accepting, change the format of the file from .json to .log

**Comment by hungrysloth128** [comment]
[Attila Fraideoux-Gilgamesh-dd0s0.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301172/Attila.Fraideoux-Gilgamesh-dd0s0.log)

[Attila Fraideoux-Gilgamesh-dd1s1.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301173/Attila.Fraideoux-Gilgamesh-dd1s1.log)

**Comment by marconsou** [comment]
What is inside _SaveSlotSelection?

**Comment by hungrysloth128** [comment]
[_SaveSlotSelection.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301181/_SaveSlotSelection.log)

**Comment by marconsou** [comment]
Ok, the dds1s1 and the SaveSlotSelection seems fine.
The dds0s0 should never happen, it seems to be a issue,

**Comment by hungrysloth128** [comment]
I'm only on the 1st (top) save file and just finished 140. But I also ran the 131-140 set w/o the plugin if that's relevant too. The last logged one in the plugin is 130

**Comment by marconsou** [comment]
Something went wrong:
The dd0s0 is a old save file which only contains the 61->70. 
It is old because it doesn't contain the data related to "How many enemies killed to open the exit" (Cairn of Passage kills) and pomanders used, maybe you installed the plugin during a save slot back then.
The dds1s1 seems in good state: it is a run from 1->130?

**Comment by marconsou** [comment]
I think in this case, you can delete the dd0s0 (the save files never should contain zeros like that)
The other save dd1s1 is the PotD slot 1, but you skipped a set, so this gonna mess the score.

**Comment by hungrysloth128** [comment]
When I do that it just opens the save file in notepad.

**Comment by marconsou** [comment]
Open the Statistic Window, click the Backups button, it will open the folder.
From there go one back one folder and you should be in the folder where contains the save file.
Copy the dd1s1 to the Backups folder.
Go back to the game, open the Statistics Window, below the Backup button should be you copied save file, click the dd1s1 there and check if it will crash

**Comment by hungrysloth128** [comment]
I have but it's not showing in the plugin. I also copied it again outside the backup folder and still nothing is there.

![Screenshot (12)](https://user-images.githubusercontent.com/60623734/209494571-eda90253-d538-486f-9530-8b9aa62f0b14.png)

**Comment by marconsou** [comment]
Ah, ok, it need to json format, or the plugin will not recognize

**Comment by hungrysloth128** [comment]
how can I convert it back?

**Comment by marconsou** [comment]
Just rename the last part of the file from .log to .json

**Comment by hungrysloth128** [comment]
ok so I tried that and nothing changed. I also now removed all save files (have a backup elsewhere) and it's still crashing
![Screenshot (14)](https://user-images.githubusercontent.com/60623734/209495624-d33d108f-fba0-48a0-9ee4-47235b77fce3.png)

Crash report:
[dalamud_appcrash_20221225_221853_514_10312.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301343/dalamud_appcrash_20221225_221853_514_10312.log)

**Comment by marconsou** [comment]
Ok, keep your game close during it and open the **%AppData%\XIVLauncher\pluginConfigs**
Copy and save somewhere the DeepDungeonTracker (folder com save files) and DeepDungeonTracker.json (config file)
Delete both
Go to %AppData%\XIVLauncher\installedPlugins
Delete the DeepDungeonTracker folder (check how many versions is in there, this is the plugin files it).
Start the game, install the plugin normally, then start a second file (any floor) kill one enemy, open a chest and leave the instance. It will generate a new save for test, them check if will open.

With this done, you gonna have a fresh plugin install and config file.

**Comment by hungrysloth128** [comment]
![Screenshot (16)](https://user-images.githubusercontent.com/60623734/209497081-3753ca3e-75b0-414b-8334-d0133dd3a440.png)
just did that. new install. no save files. same crash. game loads completely fine when plugin is disabled. second I turn it back on it crashes.

**Comment by marconsou** [comment]
Are you logout in South Shroud?
Try to Logout in other place, because when you are there, the plugin will try to automatically load the latest save file (if you don't have a save file, nothing will happen tho)
Then if no crash happen, teleport to South Shroud and check if it will crash.

**Comment by hungrysloth128** [comment]
ok so the above worked. I teleported to limsa and reinstalled the plugin and no crash. Right when I teleported to South Shroud it crashed again

**Comment by marconsou** [comment]
Do you have access to the HoH? If you do the same thing in Ruby Sea, it should crash.
Send me your Dalamud.log (not the dalamu_appcrash.log)

**Comment by hungrysloth128** [comment]
no sadly I'm still in SB MSQ

**Comment by marconsou** [comment]
Send me the dalamud.log from here: %AppData%\XIVLauncher

**Comment by hungrysloth128** [comment]
[dalamud.log](https://github.com/marconsou/deep-dungeon-tracker/files/10301467/dalamud.log)

**Comment by marconsou** [comment]
One thing you could try is the new version (still not released):  **https://easyupload.io/4u1imy**
You could put the 0.0.1.4 folder in here: **%AppData%\XIVLauncher\installedPlugins\DeepDungeonTracker**
But you need to remove the 0.0.1.3 folder to avoid conflict (keep o game closed before attempting this process)

I'm suspecting if something wrong with this version "0.0.1.3", or if something related to download from dalamud plugin page

**Comment by hungrysloth128** [comment]
ok so I'm on 0.0.1.4 and interestingly I got the plugin to load w/o crashing when I reset everything to default settings beforehand. But, the moment I stepped into floor 1 and clicked "show" for the tracker, it crashed again. 

![Screenshot (17)](https://user-images.githubusercontent.com/60623734/209508359-ef2e249d-d45f-4ca1-8513-5f345926be9b.png)

**Comment by marconsou** [comment]
If you hide all UIs, enter  floor 1, and start showing one by one, let the Tracker window for last it will crash exactly during the Tracker Window?

**Comment by hungrysloth128** [comment]
ok so this is a development. I turned all the plugin UIs off and entered palace just fine. I then turned on each UI one by one and no crash....but, when I try to open the main /ddt config, I get this: 
![Screenshot (19)](https://user-images.githubusercontent.com/60623734/209511351-20a52696-a236-4d93-a1e2-5eb05d451334.png)

Not only that, but also the same with the dalamud plugin + settings tab in general:
![Screenshot (20)](https://user-images.githubusercontent.com/60623734/209511453-b2ad77d8-bdcb-41d7-b4e4-34cfae0731d5.png)

The plugin is clearly working now there's just a weird UI thing going on

**Comment by marconsou** [comment]
There some plugins (based on the Dalamud.log) that are causing some issue with your UI, they don't crash the game, but they mess a lot with your UI.

The plugin that is causing this issue is MiniMappingway.
You might try disabling this plugin (then you need to restart the game) and after that open the Config menu, from game main menu and see if something change.

**Comment by marconsou** [comment]
Check the configuration menu of other plugin and see if there are something strange.
I think it might worth disabling all plugin, leaving only the Deep Dungeon Tracker enable, restart the game and then, check again the config menu.

This can be the cause of this issue.

**Comment by hungrysloth128** [comment]
ok i disabled every plugin except DDT and now I got the crash again after character select:
![Screenshot (22)](https://user-images.githubusercontent.com/60623734/209513758-c4c30bf8-90e9-480a-b9e7-c8f72c7acf47.png)

Here's the new crash report:
[dalamud_appcrash_20221226_014549_684_11676.log](https://github.com/marconsou/deep-dungeon-tracker/files/10302025/dalamud_appcrash_20221226_014549_684_11676.log)

**Comment by marconsou** [comment]
Ok, i think i did the same think as you and crashed the same way, one moment.

**Comment by hungrysloth128** [comment]
24

**Comment by marconsou** [comment]
The bigger font size is causing the crash

**Comment by marconsou** [comment]
Yeah, i think a found the error.
Can you test using the default 12pt?

**Comment by hungrysloth128** [comment]
dalamud or DDT?

**Comment by marconsou** [comment]
Dalamud settings, Global Font Scale: 12pt

**Comment by hungrysloth128** [comment]
woah that actually worked! now I'm just trying to get my save file back. I have it in backups here 
![Screenshot (23)](https://user-images.githubusercontent.com/60623734/209516136-14768cf4-d8c7-45c4-8363-ba87a61650f4.png)

But even when I move it outside the backup folder I still can't see the save like above? do I need to enter palace again on that first save for it to register again?
![Screenshot (24)](https://user-images.githubusercontent.com/60623734/209516340-41068819-0d1b-4ee9-a67f-607bd22921d7.png)

**Comment by marconsou** [comment]
I would recommend you to uninstall this version (0.0.1.4-dev) and install the official from dalamud menu (0.01.3).
But keep your global font scale 12pt for while. 
I've put the fix of this issue in the official 0.0.14 and should be release today. 
Then, when you get the new update (0.0.1.4 from dalamud) you can increase the size of the font again to what you were using. But for now keep it 12pt.

You dd1s1 should work for tracking stuff, but sadly you skipped a set and the score tracking might be lost.

**Comment by marconsou** [comment]
There are two SaveSlotSelection, need to open the json one and see what is inside, and delete the text document one

**Comment by hungrysloth128** [comment]
omg you fixed it!!!! Even if the score is off by that one set at least it's all working now. thank you x10000 for being so patient too. And thanks again for the help!

![Screenshot (25)](https://user-images.githubusercontent.com/60623734/209518182-0d6ec359-b067-4077-b77c-3d9d727b82c7.png)

**Comment by marconsou** [comment]
Yeah, the official update today will fix this issue (but if you keep this dev version, i think the dalamud will not notify for the new one, because both are 0.0.1.4 version).

**Comment by marconsou** [comment]
I'm about to build another release, is the issue still persist?
